### ISSUE TITLE
Error using  *  Multiplying NaN with an SDPVAR makes no sense.

### ISSUE THREAD

**Issue by LikunWang1990** [jtstoffel/tube-mpc#1]
Hi,

Thank you for the code.
However, I just got this error when I try to run run_planar_double_integrator.
I am using matlab 2023. 
Could you please helpe me solve this.

Thanks,
Likun

-------------------------------------------------
Calculating Tube Approximation Parameters ...
-------------------------------------------------
Calculating Invariant Set ...
Elapsed time is 0.207355 seconds.
FAILURE: Unable to solve for L1
    solvertime: 0
          info: 'Solver not found (mosek)'
       problem: -3
    yalmiptime: 0.0560

FAILURE: Unable to solve for M1
    solvertime: 0
          info: 'Solver not found (mosek)'
       problem: -3
    yalmiptime: 0.0480

FAILURE: Unable to solve for T1
    solvertime: 0
          info: 'Solver not found (mosek)'
       problem: -3
    yalmiptime: 0.0480

Error using  * 
Multiplying NaN with an SDPVAR makes no sense.

Error in preprocess_system (line 101)
    cons = [cons, L1'*Pa*L1 - Pa + Qa <= -tol*eye(qs)];

Error in run_planar_double_integrator (line 3)
system = preprocess_system(system, false);

**Comment by jtstoffel** [comment]
@LikunWang1990 You need to have solvers available to Yalmip for solving QPs, and SDPs. I used [MOSEK](https://www.mosek.com/products/academic-licenses/) but Sedumi would work too if you have that installed, just modify the solver options here: `opts = sdpsettings('solver','mosek','verbose',0, 'beeponproblem', []); `

**Comment by LikunWang1990** [comment]
> @LikunWang1990 You need to have solvers available to Yalmip for solving QPs, and SDPs. I used [MOSEK](https://www.mosek.com/products/academic-licenses/) but Sedumi would work too if you have that installed, just modify the solver options here: `opts = sdpsettings('solver','mosek','verbose',0, 'beeponproblem', []); `

Hi,

I just start learning tube mpc. Sorry if my question is stupid.

I think I have MOSEK installed. However, I still have problems for running the examples.

-------------------------------------------------
Calculating Tube Approximation Parameters ...
-------------------------------------------------
Calculating Invariant Set ...
Elapsed time is 0.025635 seconds.
FAILURE: Unable to solve for L1
    yalmipversion: '20210331'
    matlabversion: '9.14.0.2206163 (R2023a)'
       yalmiptime: NaN
       solvertime: NaN
             info: 'Unknown problem in solver (Turn on 'debug' in sdpsettings) (Error using call_mosek_primal↵Failure in Mosek recovery)'
          problem: 9

FAILURE: Unable to solve for M1
    yalmipversion: '20210331'
    matlabversion: '9.14.0.2206163 (R2023a)'
       yalmiptime: NaN
       solvertime: NaN
             info: 'Unknown problem in solver (Turn on 'debug' in sdpsettings) (Error using call_mosek_primal↵Failure in Mosek recovery)'
          problem: 9

FAILURE: Unable to solve for T1
    yalmipversion: '20210331'
    matlabversion: '9.14.0.2206163 (R2023a)'
       yalmiptime: NaN
       solvertime: NaN
             info: 'Unknown problem in solver (Turn on 'debug' in sdpsettings) (Error using call_mosek_primal↵Failure in Mosek recovery)'
          problem: 9

Error using  * 
Multiplying NaN with an SDPVAR makes no sense.

Error in preprocess_system (line 101)
    cons = [cons, L1'*Pa*L1 - Pa + Qa <= -tol*eye(qs)];

Error in run_double_integrator (line 3)
system = preprocess_system(system, false);


Could you also please have a look of the code below. Is there some setting incorrect??

clear; clc
system = double_integrator_model;
system = preprocess_system(system, false);
system.Qa = 0.1 * eye(system.qs); % adjust elasticity 

bc.initial_tube.z = [1;-2];
bc.initial_tube.a = ones(system.qs,1);
bc.initial_state = [1.1,2.1];
bc.final_tube.z = [0;0];
bc.final_tube.a = ones(system.qs,1);
bc.final_state = [0.1,0.1];

tube = etoc(system, 7, bc);
simdata = sim_etoc(system, tube, bc, 10, false);
plot_2D_etoc(system, tube, simdata);

Thanks inadvance!

Likun

**Comment by jtstoffel** [comment]
Add the debug flag to the Yalmip options, might give more info. The preprocessing step should work for all the examples, so there is some issue still with the solver setup. Try placing a breakpoint [here](https://github.com/jtstoffel/tube-mpc/blob/48d035d398af4ca52c9512c6f445ea6c8c7ad469/utils/preprocess_system.m#L66) and make sure all the parameters calculated using MPT3 are real values.

**Comment by LikunWang1990** [comment]
Hi,

I would like to close this, as I didn't install the mosek correctly.

Thanks,
Likun
